<?php
declare(strict_types=1);

/**
 * Art by Renee — site-inhoud (NL/EN) en collectie.
 */

return [
    'contact' => [
        'name' => ABR_CONTACT_NAME,
        'name_short' => 'R. Bult',
        'email' => ABR_CONTACT_EMAIL,
        'phone' => ABR_CONTACT_PHONE,
        'instagram_url' => 'https://www.instagram.com/renee_bult/',
        'instagram_handle' => '@renee_bult',
        'designer_url' => 'https://rrcreaties.org/',
        'designer_name' => 'RR Creaties',
    ],

    'copy' => [
        'nl' => [
            'nav' => [
                'pets' => 'Huisdieren',
                'collection' => 'Collectie',
                'about' => 'Over',
                'contact' => 'Contact',
            ],
            'eyebrow' => 'Schilderijen — acryl & mixed media',
            'hero_title' => 'Kunst die je raakt.',
            'hero_text' => 'Schilderen is voor mij een vertaling van de zielswereld — verbeeldingskracht, oneindige mogelijkheden en liefde — naar de aardse wereld. Alles mag er zijn.',
            'hero_cta' => 'Bekijk het werk',
            'commission_cta' => 'Opdracht aanvragen',
            'pets_eyebrow' => 'Specialiteit',
            'pets_title' => 'Huisdierportretten',
            'pets_text' => 'Mijn grote liefde is het schilderen van (overleden) huisdieren. Bij een opdracht is er altijd eerst persoonlijk contact. Hieronder een selectie van eerdere portretten.',
            'pets_note' => 'Voorbeelden — verkocht',
            'collection_eyebrow' => 'Wisselende collectie',
            'collection_title' => 'Beschikbaar werk',
            'collection_text' => 'Naast opdrachten is er altijd een aantal werken ter overname. Titels en prijzen staan bij elk schilderij. Status: te koop of verkocht.',
            'about_eyebrow' => 'Achter het doek',
            'about_title' => 'Zonder oordeel, met aandacht.',
            'about_quote' => '“Dat wat zich bij mij aandient, vertaal ik op doek zonder oordeel. Kunst is bedoeld om aan te raken — en elk werk vindt zijn bestemming.”',
            'about_body' => 'Ik schilder in opdracht, zowel abstract als figuratief. Alles is mogelijk. Acryl en mixed media vormen de basis van mijn werk.',
            'about_how_title' => 'Zo werkt een opdracht',
            'about_how' => 'We beginnen met een gesprek over jouw dier of idee. Daarna werk ik laag voor laag, met aandacht en intuïtie, tot het schilderij klopt.',
            'contact_eyebrow' => 'Contact',
            'contact_title' => 'Laten we samen iets maken.',
            'contact_text' => 'Stuur Renee Bult een bericht via het formulier. Je kunt ook mailen of bellen. Via Instagram deelt zij werk uit het atelier.',
            'inlichtingen' => 'Inlichtingen',
            'email' => 'E-mail',
            'phone' => 'Telefoon',
            'instagram' => 'Instagram',
            'form_eyebrow' => 'Bericht',
            'form_title' => 'Contactformulier',
            'sold' => 'Verkocht',
            'for_sale' => 'Te koop',
            'price_prefix' => '€',
            'footer_line' => 'Originele schilderijen & portretten op maat',
            'footer_credit' => 'Met ♥ ontworpen door',
            'lang_label' => 'EN',
            'form' => [
                'name' => 'Naam',
                'email' => 'E-mailadres',
                'subject' => 'Onderwerp',
                'message' => 'Bericht',
                'submit' => 'Bericht versturen',
                'sending' => 'Bezig met versturen…',
                'privacy' => 'Je naam, e-mailadres en bericht gebruiken we alleen om te reageren. We bewaren ze niet langer dan nodig en delen ze niet met derden.',
                'load_error' => 'De zegels konden niet worden geladen. Vernieuw de pagina.',
                'pick_seal' => 'Kies eerst het juiste zegel.',
                'captcha_legend' => 'Klik het gouden zegel met de letters RB',
            ],
        ],
        'en' => [
            'nav' => [
                'pets' => 'Pets',
                'collection' => 'Collection',
                'about' => 'About',
                'contact' => 'Contact',
            ],
            'eyebrow' => 'Paintings — acrylic & mixed media',
            'hero_title' => 'Art that moves you.',
            'hero_text' => 'For me, painting translates the world of the soul — imagination, endless possibility and love — into the earthly world. Everything is welcome.',
            'hero_cta' => 'View the work',
            'commission_cta' => 'Request a commission',
            'pets_eyebrow' => 'Specialty',
            'pets_title' => 'Pet portraits',
            'pets_text' => 'My greatest love is painting (departed) pets. Every commission starts with personal contact. Below is a selection of earlier portraits.',
            'pets_note' => 'Examples — sold',
            'collection_eyebrow' => 'Rotating collection',
            'collection_title' => 'Available works',
            'collection_text' => 'Alongside commissions, a number of works are always available. Each painting shows title and price, plus for sale or sold status.',
            'about_eyebrow' => 'Behind the canvas',
            'about_title' => 'Without judgment, with care.',
            'about_quote' => '“Whatever comes to me, I translate onto canvas without judgment. Art is meant to touch — and every work finds its destination.”',
            'about_body' => 'I paint on commission, both abstract and figurative. Anything is possible. Acrylic and mixed media form the base of my work.',
            'about_how_title' => 'How a commission works',
            'about_how' => 'We start with a conversation about your pet or idea. Then I work layer by layer, with attention and intuition, until the painting feels right.',
            'contact_eyebrow' => 'Contact',
            'contact_title' => "Let's make something together.",
            'contact_text' => 'Send Renee Bult a message via the form. You can also email or call. Studio work is shared on Instagram too.',
            'inlichtingen' => 'Information',
            'email' => 'Email',
            'phone' => 'Phone',
            'instagram' => 'Instagram',
            'form_eyebrow' => 'Message',
            'form_title' => 'Contact form',
            'sold' => 'Sold',
            'for_sale' => 'For sale',
            'price_prefix' => '€',
            'footer_line' => 'Original paintings & custom portraits',
            'footer_credit' => 'Designed with ♥ by',
            'lang_label' => 'NL',
            'form' => [
                'name' => 'Name',
                'email' => 'Email',
                'subject' => 'Subject',
                'message' => 'Message',
                'submit' => 'Send message',
                'sending' => 'Sending…',
                'privacy' => 'Your name, email and message are only used to reply. We do not keep them longer than needed and do not share them with third parties.',
                'load_error' => 'The seals could not be loaded. Please refresh the page.',
                'pick_seal' => 'Please choose the correct seal first.',
                'captcha_legend' => 'Click the golden seal with the letters RB',
            ],
        ],
    ],

    'pets' => [
        [
            'id' => 'samen',
            'image' => '/art/twee-katten.webp',
            'title' => ['nl' => 'Samen', 'en' => 'Together'],
            'category' => ['nl' => 'Dierportret', 'en' => 'Pet portrait'],
            'status' => 'sold',
        ],
        [
            'id' => 'trouwe-blik',
            'image' => '/art/hondenportret.webp',
            'title' => ['nl' => 'Trouwe blik', 'en' => 'Loyal gaze'],
            'category' => ['nl' => 'Dierportret', 'en' => 'Pet portrait'],
            'status' => 'sold',
        ],
        [
            'id' => 'karakter',
            'image' => '/art/kattenportret.webp',
            'title' => ['nl' => 'Karakter', 'en' => 'Character'],
            'category' => ['nl' => 'Dierportret', 'en' => 'Pet portrait'],
            'status' => 'sold',
        ],
        [
            'id' => 'drie-vrienden',
            'image' => '/art/drie-honden.webp',
            'title' => ['nl' => 'Drie vrienden', 'en' => 'Three friends'],
            'category' => ['nl' => 'Dierportret', 'en' => 'Pet portrait'],
            'status' => 'sold',
        ],
        [
            'id' => 'sheltie',
            'image' => '/art/sheltie.webp',
            'title' => ['nl' => 'Zachte blik', 'en' => 'Gentle gaze'],
            'category' => ['nl' => 'Dierportret', 'en' => 'Pet portrait'],
            'status' => 'sold',
        ],
        [
            'id' => 'chihuahua',
            'image' => '/art/chihuahua.webp',
            'title' => ['nl' => 'Klein hart', 'en' => 'Small heart'],
            'category' => ['nl' => 'Dierportret', 'en' => 'Pet portrait'],
            'status' => 'sold',
        ],
    ],

    'collection' => [
        [
            'id' => 'zomerveld',
            'image' => '/art/bloemenweide.webp',
            'title' => ['nl' => 'Zomerveld', 'en' => 'Summer field'],
            'category' => ['nl' => 'Abstract — acryl', 'en' => 'Abstract — acrylic'],
            'status' => 'sale',
            'price' => 485,
        ],
        [
            'id' => 'bloemenboeket',
            'image' => '/art/bloemenboeket.webp',
            'title' => ['nl' => 'Bloemenzee', 'en' => 'Sea of flowers'],
            'category' => ['nl' => 'Figuratie — acryl', 'en' => 'Figurative — acrylic'],
            'status' => 'sale',
            'price' => 520,
        ],
        [
            'id' => 'horizon',
            'image' => '/art/horizon.webp',
            'title' => ['nl' => 'Horizon', 'en' => 'Horizon'],
            'category' => ['nl' => 'Abstract — mixed media', 'en' => 'Abstract — mixed media'],
            'status' => 'sale',
            'price' => 420,
        ],
        [
            'id' => 'kleurvlakken',
            'image' => '/art/abstract-blokken.webp',
            'title' => ['nl' => 'Verloren schijn', 'en' => 'Lost appearance'],
            'category' => ['nl' => 'Abstract — acryl', 'en' => 'Abstract — acrylic'],
            'status' => 'sale',
            'price' => 395,
        ],
        [
            'id' => 'kleur',
            'image' => '/art/abstract-kleur.webp',
            'title' => ['nl' => 'Hartslag', 'en' => 'Heartbeat'],
            'category' => ['nl' => 'Abstract — mixed media', 'en' => 'Abstract — mixed media'],
            'status' => 'sold',
        ],
        [
            'id' => 'lichten',
            'image' => '/art/abstract-lichten.webp',
            'title' => ['nl' => 'Lichten', 'en' => 'Lights'],
            'category' => ['nl' => 'Abstract — acryl', 'en' => 'Abstract — acrylic'],
            'status' => 'sale',
            'price' => 410,
        ],
        [
            'id' => 'strepen',
            'image' => '/art/abstract-strepen.webp',
            'title' => ['nl' => 'Lagen', 'en' => 'Layers'],
            'category' => ['nl' => 'Abstract — acryl', 'en' => 'Abstract — acrylic'],
            'status' => 'sold',
        ],
        [
            'id' => 'muurstuk',
            'image' => '/art/abstract-muur.webp',
            'title' => ['nl' => 'Grote adem', 'en' => 'Deep breath'],
            'category' => ['nl' => 'Abstract — acryl', 'en' => 'Abstract — acrylic'],
            'status' => 'sale',
            'price' => 890,
        ],
        [
            'id' => 'atelier',
            'image' => '/art/atelier-ezel.webp',
            'title' => ['nl' => 'Op de ezel', 'en' => 'On the easel'],
            'category' => ['nl' => 'Abstract — acryl', 'en' => 'Abstract — acrylic'],
            'status' => 'sold',
        ],
    ],
];
